### ISSUE TITLE
Module is incompatible with foundry v12

### ISSUE THREAD

**Issue by KamiliaBlow** [MiahNelah/audio-preview#6]
The play button does not appear in the file explorer.

```This is *not* a libWrapper bug.

Find information about this module here: https://github.com/MiahNelah/audio-preview

Ask the community for support:
- FoundryVTT Discord's #modules-troubleshooting channel: https://discord.gg/foundryvtt
- FoundryVTT Reddit: https://www.reddit.com/r/FoundryVTT

== Technical Details:
Detected by libWrapper.
Package ID= audio-preview
Error= Can't wrap 'FilePicker.prototype._onPick', target does not exist or could not be found.

    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at de (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at Object.fn (audio-preview.js:123:16)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at Game.initialize (foundry.js:8885:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
🎁constructor @ libWrapper-wrapper.js:111
(анонимный) @ libWrapper-api.js:82
de @ libWrapper-api.js:155
🎁register @ libWrapper-api.js:525
(анонимный) @ audio-preview.js:123
#call @ foundry.js:608
callAll @ foundry.js:565
initialize @ foundry.js:8885
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁libWrapperInit @ libWrapper-api.js:805
await in 🎁libWrapperInit (асинхронно)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:95263
foundry.js:7621 Foundry VTT | Loaded localization file modules/audio-preview/module/languages/en.json
foundry.js:71330  Audio Preview: Error detected in module. It is likely this module has not been updated for FVTT Version 12 Stable. (See JS Console)
fetch @ foundry.js:71330
notify @ foundry.js:71226
🎁call_wrapped @ libWrapper-wrapper.js:507
notificationNotify @ utils.js:4999
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Notifications.prototype.notify#0 @ libWrapper-wrapper.js:189
error @ foundry.js:71263
🎁_ui @ libWrapper-notifications.js:74
#call @ foundry.js:608
callAll @ foundry.js:565
setupGame @ foundry.js:9000
await in setupGame (асинхронно)
_initializeGameView @ foundry.js:10310
_initializeView @ foundry.js:10286
initialize @ foundry.js:8900
await in initialize (асинхронно)
🎁call_wrapped @ libWrapper-wrapper.js:507
🎁libWrapperInit @ libWrapper-api.js:805
await in 🎁libWrapperInit (асинхронно)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:95263
```

**Comment by MiahNelah** [comment]
A new version has been released (v1.2.3). I rushed it a bit, but everything looks fine. Please open a new issue if you get some problems with it.
